title: "Michael Tung"
description: "Personal website for my CV/Resume and research experience"
theme: minima

# Additional options
author: Michael Tung
email: xxxxx@example.com
social:
  github: GodKnowss
  linkedin: abcd

# Example of navigation control in _config.yml (check your theme documentation for specifics)
nav:
  - title: "Home"
    url: /
  - title: "CV"
    url: /cv.md
  - title: "Research"
    url: /research.html
