title: "Michael Tung"
description: "Personal website for my CV/Resume and research experience"
theme: minima

# Additional options
author: Michael Tung
email: xxxxx@example.com
social:
  github: GodKnowss
  linkedin: abcd

# Define the order of navigation links
header_pages:
  - index.md       # Home page
  - cv.md          # CV page
  - research.md    # Research page
  - coursework.md     # Coursework page
  - contact.md     # Contact page
